name: Package WoW Addon

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug zip file name
        run: |
          echo "Expected zip: ChattyLittleNpc_Warlords_of_Draenor_voiceovers-${{ github.ref_name }}.zip"
          ls -lh
                    
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate VoiceoversList.lua
        run: |
          cd ChattyLittleNpc_Warlords_of_Draenor_voiceovers
          python generate_voicovers_list_file.py


      - name: Create Addon ZIP
        run: |
          zip -r "ChattyLittleNpc_Warlords_of_Draenor_voiceovers-${{ github.ref_name }}.zip" ChattyLittleNpc_Warlords_of_Draenor_voiceovers

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "ChattyLittleNpc_Warlords_of_Draenor_voiceovers-${{ github.ref_name }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
